### ISSUE TITLE
can you please specify the training procedure ,like there is no training and testing script ,it will be very great if you can provide these details .

### ISSUE THREAD

**Issue by sivasingireddi** [tpinetz/low-dose-gadolinium-mri-synthesis#1]

**Comment by tpinetz** [comment]
Sorry, for the late response. The notification got unfortunately lost and I did not check the repository in a while. I did not add the training script, due to using hdf5 databases, which stores preprocessed dicom arrays with all kinds of additional information. As I am not allowed to share this dicom dataset, I did not feel like the additionally work in getting this code readable was warranted. What you need for training this model is a data loader which provides the necessary images and metadata. I can update the repository with our data loader regardless.
